#!/bin/bash

FIRSTFILE=$1
FIRSTFILESIZE=$(stat -c%s "$FIRSTFILE")
SECONDFILE=$2
SECONDFILESIZE=$(stat -c%s "$SECONDFILE")
echo "$FIRSTFILE => $FIRSTFILESIZE bytes"
echo "$SECONDFILE => $SECONDFILESIZE bytes"